GET http://localhost:3000/ping

###
GET http://localhost:3000/api/queue

### 
GET http://localhost:3000/getArchived

###
GET http://localhost:3000/resolverandom

###
POST http://localhost:3000/api/queue
Content-Type: application/json

{
  "requestorDisplayName": "a",
  "requestorId": "b"
}