###
GET http://localhost:3001/api/student/scislowski-usd266

###
GET http://localhost:3001/api/student/mrscislowski

###
POST http://localhost:3001/api/student/scislowski-usd266
Content-Type: application/json

{
  "queueId": "655ea96eb694908fcfa3260c"
}

###
POST http://localhost:3001/api/student/scislowski-usd266