
###
GET http://localhost:3000/api/queue

### 
GET http://localhost:3000/api/archived

###
POST http://localhost:3000/api/queue
Content-Type: application/json

{
  "user": {
    "id": "b",
    "displayName": "b"
  }
}

###
POST http://localhost:3000/api/queue/64db7a1b2fc5cff00d792e05
Content-Type: application/json

{
  "user": {
    "id": "b",
    "displayName": "b"
  },
  "resolutionStatus": "cancel"
}

###
POST http://localhost:3000/api/clear

###
POST http://localhost:3000/api/fillrandom